name: Legendchat
author: SubZero0
main: br.com.devpaulo.legendchat.Main
version: 1.1.3
softdepend: [Vault, PlaceholderAPI]
load: STARTUP
website: www.devpaulo.com.br
commands:
   legendchat:
      description: Legendchat main command.
      usage: /<command>
      aliases: lc
   channel:
      description: Change your channel.
      usage: /<command>
      aliases: ch
   afk:
      description: Activate/Deactivate afk.
      usage: /<command> [motive]
   ignore:
      description: Ignore a player.
      usage: /<command> <player>
   tempchannel:
      description: Temporary channel main command.
      usage: /<command>
      aliases: tc
   mute:
      description: Ignore a channel.
      usage: /<command> <channel>
